<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>StudyFlow - Quản lý học tập</title>
    <style>
        :root{--brand:#4f46e5;--brand2:#7c3aed;--bg:#f4f6fb;--text:#172033;--muted:#687086;--line:#e5e7ef;--danger:#dc2626;--ok:#059669}
        *{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Segoe UI,sans-serif;background:var(--bg);color:var(--text)}button,input,select,textarea{font:inherit}.hidden{display:none!important}
        .auth{min-height:100vh;display:grid;place-items:center;padding:24px;background:linear-gradient(135deg,#eef2ff,#f5f3ff)}.auth-card{width:min(430px,100%);background:white;border-radius:22px;padding:32px;box-shadow:0 25px 70px #312e8120}.logo{font-size:25px;font-weight:800;color:var(--brand)}.subtitle{color:var(--muted);margin:8px 0 24px}.tabs{display:flex;background:#f3f4f6;padding:4px;border-radius:11px;margin-bottom:20px}.tabs button{flex:1;border:0;background:none;padding:9px;border-radius:8px;cursor:pointer}.tabs .active{background:white;color:var(--brand);font-weight:700;box-shadow:0 2px 8px #00000012}
        label{display:block;font-size:13px;font-weight:650;margin:13px 0 6px}.input{width:100%;border:1px solid var(--line);border-radius:9px;padding:10px 12px;background:white;outline:none}.input:focus{border-color:var(--brand);box-shadow:0 0 0 3px #4f46e51a}textarea.input{min-height:90px;resize:vertical}.btn{border:0;border-radius:9px;padding:10px 15px;cursor:pointer;font-weight:650}.btn-primary{background:linear-gradient(135deg,var(--brand),var(--brand2));color:white}.btn-soft{background:#eef2ff;color:var(--brand)}.btn-danger{background:#fef2f2;color:var(--danger)}.btn-block{width:100%;margin-top:18px}
        .app{min-height:100vh}.sidebar{position:fixed;inset:0 auto 0 0;width:245px;background:#111827;color:#d1d5db;padding:22px 15px;z-index:5}.sidebar .logo{color:white;padding:0 10px 20px}.nav button{display:flex;width:100%;border:0;color:inherit;background:none;text-align:left;padding:11px 13px;border-radius:9px;margin:2px 0;cursor:pointer}.nav button:hover,.nav button.active{background:#ffffff14;color:white}.main{margin-left:245px}.topbar{height:70px;background:white;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0;z-index:4}.content{padding:26px;max-width:1500px;margin:auto}.page-head{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:20px}.page-head h1{font-size:24px;margin:0}.muted{color:var(--muted)}
        .grid{display:grid;gap:16px}.stats{grid-template-columns:repeat(5,1fr)}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:0 4px 16px #11182708}.stat strong{display:block;font-size:28px;margin-top:10px}.two{grid-template-columns:1fr 1fr}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:15px}.filters .input{width:auto;min-width:150px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:12px 10px;text-align:left;border-bottom:1px solid var(--line);font-size:14px}.table th{color:var(--muted);font-size:12px;text-transform:uppercase}.actions{display:flex;gap:6px}.badge{display:inline-flex;padding:4px 8px;border-radius:99px;background:#eef2ff;color:var(--brand);font-size:12px;font-weight:700}.badge.danger{background:#fef2f2;color:var(--danger)}.badge.ok{background:#ecfdf5;color:var(--ok)}
        .modal-bg{position:fixed;inset:0;background:#11182799;display:grid;place-items:center;z-index:20;padding:20px}.modal{width:min(620px,100%);max-height:90vh;overflow:auto;background:white;border-radius:16px;padding:22px}.modal-head{display:flex;justify-content:space-between;align-items:center}.modal-head h2{margin:0}.close{border:0;background:none;font-size:25px;cursor:pointer}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.full{grid-column:1/-1}.toast{position:fixed;right:20px;bottom:20px;background:#111827;color:white;border-radius:10px;padding:12px 18px;z-index:30;box-shadow:0 10px 30px #0003}.mobile-menu{display:none}.empty{text-align:center;color:var(--muted);padding:35px}
        @media(max-width:900px){.stats{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.sidebar{transform:translateX(-100%);transition:.2s}.sidebar.open{transform:none}.main{margin-left:0}.mobile-menu{display:inline-block}.topbar{padding:0 16px}.content{padding:18px}.form-grid{grid-template-columns:1fr}.full{grid-column:auto}}
        @media(max-width:520px){.stats{grid-template-columns:1fr}.auth-card{padding:23px}.page-head{align-items:flex-start;flex-direction:column}.page-head .btn{width:100%}}
    </style>
</head>
<body>
<section id="auth" class="auth">
 <div class="auth-card"><div class="logo">◈ StudyFlow</div><p class="subtitle">Quản lý ghi chú và deadline học tập</p>
  <div class="tabs"><button id="loginTab" class="active" onclick="showAuth('login')">Đăng nhập</button><button id="registerTab" onclick="showAuth('register')">Đăng ký</button></div>
  <form id="loginForm"><label>Email</label><input class="input" name="email" type="email" required><label>Mật khẩu</label><input class="input" name="password" type="password" required><button class="btn btn-primary btn-block">Đăng nhập</button></form>
  <form id="registerForm" class="hidden"><label>Họ tên</label><input class="input" name="name" required><label>Email</label><input class="input" name="email" type="email" required><label>Mật khẩu</label><input class="input" name="password" type="password" minlength="8" required><label>Xác nhận mật khẩu</label><input class="input" name="password_confirmation" type="password" required><button class="btn btn-primary btn-block">Tạo tài khoản</button></form>
 </div>
</section>
<section id="app" class="app hidden">
 <aside id="sidebar" class="sidebar"><div class="logo">◈ StudyFlow</div><nav id="nav" class="nav">
  <button data-page="dashboard">▦ &nbsp; Dashboard</button><button data-page="subjects">▤ &nbsp; Môn học</button><button data-page="notes">▧ &nbsp; Ghi chú</button><button data-page="deadlines">◷ &nbsp; Deadline</button><button data-page="documents">▣ &nbsp; Tài liệu</button><button data-page="tags">⌑ &nbsp; Tag</button><button data-page="profile">◉ &nbsp; Tài khoản</button><button id="adminNav" data-page="admin" class="hidden">⚙ &nbsp; Quản trị</button>
 </nav></aside>
 <main class="main"><header class="topbar"><button class="btn btn-soft mobile-menu" onclick="sidebar.classList.toggle('open')">☰</button><strong id="pageTitle">Dashboard</strong><div><span id="userName"></span> <button class="btn btn-soft" onclick="logout()">Đăng xuất</button></div></header><div id="content" class="content"></div></main>
</section>
<div id="modalRoot"></div><div id="toast" class="toast hidden"></div>
<script>
const API='/api', state={token:localStorage.getItem('token'),user:null,subjects:[],tags:[],page:'dashboard'};
const labels={dashboard:'Dashboard',subjects:'Môn học',notes:'Ghi chú',deadlines:'Deadline',documents:'Tài liệu',tags:'Tag',profile:'Tài khoản',admin:'Quản trị'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2800)}
async function api(path,opt={}){opt.headers={Accept:'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{}) ,...(opt.headers||{})};if(opt.body&&!(opt.body instanceof FormData)){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}const r=await fetch(API+path,opt);if(r.status===401){localStorage.removeItem('token');location.reload()}let data;try{data=await r.json()}catch{data={message:'Phản hồi không hợp lệ'}}if(!r.ok)throw new Error(data.message||Object.values(data.errors||{}).flat()[0]||'Có lỗi xảy ra');for(const key of ['subjects','tags','notes']){if(Array.isArray(data.data?.[key]))data.data[key].data=data.data[key]}return data}
function showAuth(type){loginForm.classList.toggle('hidden',type!=='login');registerForm.classList.toggle('hidden',type!=='register');loginTab.classList.toggle('active',type==='login');registerTab.classList.toggle('active',type==='register')}
loginForm.onsubmit=async e=>{e.preventDefault();try{const d=await api('/login',{method:'POST',body:Object.fromEntries(new FormData(e.target))});state.token=d.data.token;localStorage.setItem('token',state.token);await boot()}catch(x){toast(x.message)}};
registerForm.onsubmit=async e=>{e.preventDefault();try{const d=await api('/register',{method:'POST',body:Object.fromEntries(new FormData(e.target))});state.token=d.data.token;localStorage.setItem('token',state.token);await boot()}catch(x){toast(x.message)}};
async function boot(){try{state.user=(await api('/me')).data.user;auth.classList.add('hidden');app.classList.remove('hidden');userName.textContent=state.user.name;adminNav.classList.toggle('hidden',state.user.role!=='admin');await Promise.all([loadSubjects(),loadTags()]);navigate('dashboard')}catch{state.token=null;localStorage.removeItem('token');auth.classList.remove('hidden');app.classList.add('hidden')}}
async function logout(){try{await api('/logout',{method:'POST'})}catch{}localStorage.removeItem('token');location.reload()}
nav.onclick=e=>{const b=e.target.closest('[data-page]');if(b)navigate(b.dataset.page)};
async function navigate(page){state.page=page;pageTitle.textContent=labels[page];document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));sidebar.classList.remove('open');content.innerHTML='<div class="card">Đang tải...</div>';try{await ({dashboard:renderDashboard,subjects:renderSubjects,notes:renderNotes,deadlines:renderDeadlines,documents:renderDocuments,tags:renderTags,profile:renderProfile,admin:renderAdmin}[page])()}catch(e){content.innerHTML=`<div class="card">${esc(e.message)}</div>`}}
async function loadSubjects(){const d=await api('/subjects?per_page=100');state.subjects=d.data.subjects.data}
async function loadTags(){const d=await api('/tags?per_page=100');state.tags=d.data.tags.data}
const subjectOptions=(v='')=>'<option value="">Không chọn</option>'+state.subjects.map(s=>`<option value="${s.id}" ${s.id==v?'selected':''}>${esc(s.name)}</option>`).join('');
const tagChecks=(selected=[])=>state.tags.map(t=>`<label style="display:inline-flex;margin-right:12px"><input type="checkbox" name="tag_ids[]" value="${t.id}" ${selected.includes(t.id)?'checked':''}> ${esc(t.name)}</label>`).join('');
function stats(items){return `<div class="grid stats">${items.map(([k,v])=>`<div class="card stat"><span class="muted">${k}</span><strong>${v}</strong></div>`).join('')}</div>`}
async function renderDashboard(){const x=(await api('/dashboard')).data;content.innerHTML=`<div class="page-head"><div><h1>Xin chào, ${esc(state.user.name)}!</h1><div class="muted">Tổng quan hoạt động học tập của bạn</div></div></div>${stats([['Môn học',x.summary.total_subjects],['Ghi chú',x.summary.total_notes],['Deadline',x.summary.total_deadlines],['Tài liệu',x.summary.total_documents],['Quá hạn',x.deadline_stats.overdue]])}<div class="grid two" style="margin-top:16px"><div class="card"><h3>Deadline 7 ngày tới</h3>${x.upcoming_deadlines.length?x.upcoming_deadlines.map(d=>`<p><b>${esc(d.title)}</b><br><span class="muted">${new Date(d.due_at).toLocaleString('vi-VN')}</span></p>`).join(''):'<div class="empty">Không có deadline sắp tới</div>'}</div><div class="card"><h3>Ghi chú mới nhất</h3>${x.latest_notes.length?x.latest_notes.map(n=>`<p><b>${esc(n.title)}</b><br><span class="muted">${esc((n.content||'').slice(0,90))}</span></p>`).join(''):'<div class="empty">Chưa có ghi chú</div>'}</div></div>`}
function table(head,rows){return `<div class="card table-wrap"><table class="table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${head.length}" class="empty">Chưa có dữ liệu</td></tr>`}</tbody></table></div>`}
async function renderSubjects(){const d=(await api('/subjects?per_page=100')).data.subjects.data;state.subjects=d;content.innerHTML=`<div class="page-head"><div><h1>Môn học</h1><div class="muted">Phân loại nội dung theo môn</div></div><button class="btn btn-primary" onclick="subjectModal()">+ Thêm môn học</button></div>${table(['Môn học','Mã','Giảng viên','Trạng thái',''],d.map(s=>`<tr><td><b style="color:${esc(s.color||'#4f46e5')}">${esc(s.name)}</b></td><td>${esc(s.code||'-')}</td><td>${esc(s.teacher_name||'-')}</td><td><span class="badge">${s.status==='active'?'Đang học':'Lưu trữ'}</span></td><td class="actions"><button class="btn btn-soft" onclick='subjectModal(${JSON.stringify(s)})'>Sửa</button><button class="btn btn-danger" onclick="remove('/subjects/${s.id}',renderSubjects)">Xóa</button></td></tr>`).join(''))}`}
function modal(title,body,onSubmit){modalRoot.innerHTML=`<div class="modal-bg" onclick="if(event.target===this)closeModal()"><form id="modalForm" class="modal"><div class="modal-head"><h2>${title}</h2><button type="button" class="close" onclick="closeModal()">×</button></div>${body}<button class="btn btn-primary btn-block">Lưu</button></form></div>`;modalForm.onsubmit=onSubmit}
function closeModal(){modalRoot.innerHTML=''}
function subjectModal(s={}){modal(s.id?'Sửa môn học':'Thêm môn học',`<div class="form-grid"><div class="full"><label>Tên môn học</label><input class="input" name="name" value="${esc(s.name)}" required></div><div><label>Mã môn</label><input class="input" name="code" value="${esc(s.code)}"></div><div><label>Giảng viên</label><input class="input" name="teacher_name" value="${esc(s.teacher_name)}"></div><div><label>Màu</label><input class="input" type="color" name="color" value="${esc(s.color||'#4f46e5')}"></div><div><label>Trạng thái</label><select class="input" name="status"><option value="active">Đang học</option><option value="archived" ${s.status==='archived'?'selected':''}>Lưu trữ</option></select></div><div class="full"><label>Mô tả</label><textarea class="input" name="description">${esc(s.description)}</textarea></div></div>`,e=>saveForm(e,s.id?`/subjects/${s.id}`:'/subjects',s.id?'PUT':'POST',renderSubjects))}
async function renderNotes(){const d=(await api('/notes?per_page=100')).data.notes.data;content.innerHTML=`<div class="page-head"><div><h1>Ghi chú</h1><div class="muted">Lưu lại kiến thức quan trọng</div></div><button class="btn btn-primary" onclick="noteModal()">+ Thêm ghi chú</button></div>${table(['Tiêu đề','Môn học','Tag','Ghim',''],d.map(n=>`<tr><td><b>${esc(n.title)}</b><br><span class="muted">${esc((n.content||'').slice(0,80))}</span></td><td>${esc(n.subject?.name||'-')}</td><td>${(n.tags||[]).map(t=>`<span class="badge">${esc(t.name)}</span>`).join(' ')}</td><td>${n.is_pinned?'★':'☆'}</td><td class="actions"><button class="btn btn-soft" onclick='noteModal(${JSON.stringify(n)})'>Sửa</button><button class="btn btn-soft" onclick="request('/notes/${n.id}/pin','PATCH',{},renderNotes)">Ghim</button><button class="btn btn-danger" onclick="remove('/notes/${n.id}',renderNotes)">Xóa</button></td></tr>`).join(''))}`}
function noteModal(n={}){modal(n.id?'Sửa ghi chú':'Thêm ghi chú',`<label>Tiêu đề</label><input class="input" name="title" value="${esc(n.title)}" required><label>Môn học</label><select class="input" name="subject_id">${subjectOptions(n.subject_id)}</select><label>Nội dung</label><textarea class="input" name="content">${esc(n.content)}</textarea><label><input type="checkbox" name="is_pinned" value="1" ${n.is_pinned?'checked':''}> Ghim ghi chú</label><label>Tag</label><div>${tagChecks((n.tags||[]).map(t=>t.id))||'<span class="muted">Chưa có tag</span>'}</div><input type="hidden" name="visibility" value="private">`,e=>saveForm(e,n.id?`/notes/${n.id}`:'/notes',n.id?'PUT':'POST',renderNotes,true))}
async function renderDeadlines(){const d=(await api('/deadlines?per_page=100')).data.deadlines.data;const status={pending:'Chưa làm',in_progress:'Đang làm',completed:'Hoàn thành',cancelled:'Đã hủy'};content.innerHTML=`<div class="page-head"><div><h1>Deadline</h1><div class="muted">Theo dõi công việc và hạn nộp</div></div><button class="btn btn-primary" onclick="deadlineModal()">+ Thêm deadline</button></div>${table(['Công việc','Môn','Hạn','Ưu tiên','Trạng thái',''],d.map(x=>{const overdue=new Date(x.due_at)<new Date()&&!['completed','cancelled'].includes(x.status);return `<tr><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.type)}</span></td><td>${esc(x.subject?.name||'-')}</td><td><span class="badge ${overdue?'danger':''}">${new Date(x.due_at).toLocaleString('vi-VN')}</span></td><td>${esc(x.priority)}</td><td>${status[x.status]}</td><td class="actions"><button class="btn btn-soft" onclick='deadlineModal(${JSON.stringify(x)})'>Sửa</button><button class="btn btn-danger" onclick="remove('/deadlines/${x.id}',renderDeadlines)">Xóa</button></td></tr>`}).join(''))}`}
function deadlineModal(d={}){const dt=d.due_at?new Date(d.due_at).toISOString().slice(0,16):'';modal(d.id?'Sửa deadline':'Thêm deadline',`<div class="form-grid"><div class="full"><label>Tiêu đề</label><input class="input" name="title" value="${esc(d.title)}" required></div><div><label>Môn học</label><select class="input" name="subject_id">${subjectOptions(d.subject_id)}</select></div><div><label>Thời hạn</label><input class="input" type="datetime-local" name="due_at" value="${dt}" required></div><div><label>Loại</label><select class="input" name="type">${[['assignment','Bài tập'],['exam','Lịch thi'],['presentation','Thuyết trình'],['project','Đồ án'],['other','Khác']].map(x=>`<option value="${x[0]}" ${d.type===x[0]?'selected':''}>${x[1]}</option>`)}</select></div><div><label>Ưu tiên</label><select class="input" name="priority">${['low','medium','high'].map(x=>`<option ${d.priority===x?'selected':''}>${x}</option>`)}</select></div><div><label>Trạng thái</label><select class="input" name="status">${['pending','in_progress','completed','cancelled'].map(x=>`<option ${d.status===x?'selected':''}>${x}</option>`)}</select></div><div class="full"><label>Mô tả</label><textarea class="input" name="description">${esc(d.description)}</textarea></div></div>`,e=>saveForm(e,d.id?`/deadlines/${d.id}`:'/deadlines',d.id?'PUT':'POST',renderDeadlines))}
async function renderDocuments(){const d=(await api('/documents?per_page=100')).data.documents.data;content.innerHTML=`<div class="page-head"><div><h1>Tài liệu</h1><div class="muted">File học tập của bạn (tối đa 10MB)</div></div><button class="btn btn-primary" onclick="documentModal()">+ Upload tài liệu</button></div>${table(['Tài liệu','Môn','Loại','Dung lượng',''],d.map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.original_name)}</span></td><td>${esc(x.subject?.name||'-')}</td><td><span class="badge">${esc(x.extension)}</span></td><td>${(x.file_size/1024).toFixed(1)} KB</td><td class="actions"><button class="btn btn-soft" onclick="downloadDoc(${x.id},'${esc(x.original_name)}')">Tải</button><button class="btn btn-danger" onclick="remove('/documents/${x.id}',renderDocuments)">Xóa</button></td></tr>`).join(''))}`}
function documentModal(){modal('Upload tài liệu',`<label>Tiêu đề</label><input class="input" name="title" required><label>Môn học</label><select class="input" name="subject_id">${subjectOptions()}</select><label>Mô tả</label><textarea class="input" name="description"></textarea><label>File</label><input class="input" type="file" name="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.jpg,.jpeg,.png" required>`,async e=>{e.preventDefault();try{await api('/documents',{method:'POST',body:new FormData(e.target)});closeModal();toast('Upload thành công');renderDocuments()}catch(x){toast(x.message)}})}
async function downloadDoc(id,name){const r=await fetch(`${API}/documents/${id}/download`,{headers:{Authorization:`Bearer ${state.token}`}});if(!r.ok)return toast('Không tải được file');const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function renderTags(){const d=(await api('/tags?per_page=100')).data.tags.data;state.tags=d;content.innerHTML=`<div class="page-head"><div><h1>Tag</h1><div class="muted">Nhãn phân loại ghi chú</div></div><button class="btn btn-primary" onclick="tagModal()">+ Thêm tag</button></div>${table(['Tên','Màu','Số ghi chú',''],d.map(t=>`<tr><td><b>${esc(t.name)}</b></td><td><span class="badge" style="color:${esc(t.color)}">${esc(t.color)}</span></td><td>${t.notes_count??0}</td><td class="actions"><button class="btn btn-soft" onclick='tagModal(${JSON.stringify(t)})'>Sửa</button><button class="btn btn-danger" onclick="remove('/tags/${t.id}',renderTags)">Xóa</button></td></tr>`).join(''))}`}
function tagModal(t={}){modal(t.id?'Sửa tag':'Thêm tag',`<label>Tên tag</label><input class="input" name="name" value="${esc(t.name)}" required><label>Màu</label><input class="input" type="color" name="color" value="${esc(t.color||'#4f46e5')}">`,e=>saveForm(e,t.id?`/tags/${t.id}`:'/tags',t.id?'PUT':'POST',async()=>{await loadTags();renderTags()}))}
async function renderProfile(){const u=state.user;content.innerHTML=`<div class="page-head"><div><h1>Tài khoản cá nhân</h1><div class="muted">Cập nhật thông tin và mật khẩu</div></div></div><div class="grid two"><form id="profileForm" class="card"><h3>Thông tin cá nhân</h3><label>Họ tên</label><input class="input" name="name" value="${esc(u.name)}" required><label>Email</label><input class="input" type="email" name="email" value="${esc(u.email)}" required><label>Mã sinh viên</label><input class="input" name="student_code" value="${esc(u.student_code)}"><label>Số điện thoại</label><input class="input" name="phone" value="${esc(u.phone)}"><label>Ảnh đại diện</label><input class="input" type="file" name="avatar" accept="image/*"><button class="btn btn-primary btn-block">Cập nhật</button></form><form id="passwordForm" class="card"><h3>Đổi mật khẩu</h3><label>Mật khẩu hiện tại</label><input class="input" type="password" name="current_password" required><label>Mật khẩu mới</label><input class="input" type="password" name="password" minlength="8" required><label>Xác nhận mật khẩu</label><input class="input" type="password" name="password_confirmation" required><button class="btn btn-primary btn-block">Đổi mật khẩu</button></form></div>`;profileForm.onsubmit=async e=>{e.preventDefault();try{const d=await api('/profile',{method:'POST',body:new FormData(e.target)});state.user=d.data.user;userName.textContent=state.user.name;toast(d.message)}catch(x){toast(x.message)}};passwordForm.onsubmit=e=>saveForm(e,'/profile/password','PUT',()=>{e.target.reset()})}
async function renderAdmin(){const [s,u]=await Promise.all([api('/admin/dashboard'),api('/admin/users')]);const users=u.data.users.data;content.innerHTML=`<div class="page-head"><div><h1>Quản trị hệ thống</h1><div class="muted">Thống kê và quản lý tài khoản</div></div></div>${stats(Object.entries(s.data.summary).map(([k,v])=>[({users:'Người dùng',subjects:'Môn học',notes:'Ghi chú',deadlines:'Deadline',documents:'Tài liệu'})[k],v]))}<div style="margin-top:16px">${table(['Người dùng','Email','Vai trò','Dữ liệu','Trạng thái',''],users.map(x=>`<tr><td><b>${esc(x.name)}</b><br>${esc(x.student_code||'')}</td><td>${esc(x.email)}</td><td>${esc(x.role)}</td><td>${x.subjects_count} môn · ${x.notes_count} ghi chú · ${x.deadlines_count} deadline</td><td><span class="badge ${x.status?'ok':'danger'}">${x.status?'Hoạt động':'Bị khóa'}</span></td><td>${x.id!==state.user.id?`<button class="btn ${x.status?'btn-danger':'btn-soft'}" onclick="request('/admin/users/${x.id}/status','PATCH',{},renderAdmin)">${x.status?'Khóa':'Mở khóa'}</button>`:''}</td></tr>`).join(''))}</div>`}
async function saveForm(e,path,method,done,arrayTags=false){e.preventDefault();const fd=new FormData(e.target),body={};for(const [k,v] of fd){if(k.endsWith('[]'))(body[k.slice(0,-2)]??=[]).push(+v);else body[k]=v}if('is_pinned' in body)body.is_pinned=!!body.is_pinned;else if(arrayTags)body.is_pinned=false;if(body.subject_id==='')body.subject_id=null;try{const d=await api(path,{method,body});closeModal();toast(d.message||'Đã lưu');await done()}catch(x){toast(x.message)}}
async function request(path,method,body,done){try{const d=await api(path,{method,body});toast(d.message||'Thành công');await done()}catch(x){toast(x.message)}}
async function remove(path,done){if(confirm('Bạn chắc chắn muốn xóa?'))await request(path,'DELETE',null,done)}
function enhanceTables(){document.querySelectorAll('#content .table-wrap:not([data-enhanced])').forEach(w=>{w.dataset.enhanced='1';const rows=[...w.querySelectorAll('tbody tr')];if(!rows.length)return;let page=1,query='';const toolbar=document.createElement('div');toolbar.className='filters';toolbar.innerHTML='<input class="input" placeholder="Tìm trong danh sách..."><select class="input"><option value="">Tất cả trạng thái</option></select><span class="muted" style="align-self:center"></span>';const values=new Set();rows.forEach(r=>r.querySelectorAll('.badge').forEach(b=>{const v=b.textContent.trim();if(v)values.add(v)}));const select=toolbar.querySelector('select');[...values].sort().forEach(v=>select.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));if(!values.size)select.classList.add('hidden');const pager=document.createElement('div');pager.className='actions';pager.style.cssText='justify-content:flex-end;margin:14px 0 20px';w.before(toolbar);w.after(pager);const draw=()=>{const filter=select.value.toLowerCase(),matched=rows.filter(r=>r.textContent.toLowerCase().includes(query)&&(!filter||[...r.querySelectorAll('.badge')].some(b=>b.textContent.trim().toLowerCase()===filter)));const pages=Math.max(1,Math.ceil(matched.length/10));page=Math.max(1,Math.min(page,pages));rows.forEach(r=>r.classList.add('hidden'));matched.slice((page-1)*10,page*10).forEach(r=>r.classList.remove('hidden'));toolbar.querySelector('span').textContent=`${matched.length} kết quả`;pager.innerHTML=`<button class="btn btn-soft" ${page<=1?'disabled':''}>←</button><span class="muted" style="align-self:center">Trang ${page}/${pages}</span><button class="btn btn-soft" ${page>=pages?'disabled':''}>→</button>`;const bs=pager.querySelectorAll('button');bs[0].onclick=()=>{page--;draw()};bs[1].onclick=()=>{page++;draw()}};toolbar.querySelector('input').oninput=e=>{query=e.target.value.toLowerCase();page=1;draw()};select.onchange=()=>{page=1;draw()};draw()});if(state.page==='admin'&&!document.querySelector('#adminDetails'))loadAdminDetails()}
async function loadAdminDetails(){const root=document.createElement('div');root.id='adminDetails';root.innerHTML='<div class="card">Đang tải dữ liệu toàn hệ thống...</div>';content.append(root);try{const [s,d]=await Promise.all([api('/admin/subjects'),api('/admin/deadlines')]);const subjects=s.data.subjects.data,deadlines=d.data.deadlines.data;root.innerHTML=`<h2>Môn học toàn hệ thống</h2>${table(['Môn học','Sinh viên','Mã','Trạng thái'],subjects.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.user?.name||'-')}</td><td>${esc(x.code||'-')}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join(''))}<h2>Deadline toàn hệ thống</h2>${table(['Deadline','Sinh viên','Môn học','Thời hạn','Trạng thái'],deadlines.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.user?.name||'-')}</td><td>${esc(x.subject?.name||'-')}</td><td>${new Date(x.due_at).toLocaleString('vi-VN')}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join(''))}`}catch(e){root.innerHTML=`<div class="card">${esc(e.message)}</div>`}}
const tableObserver=new MutationObserver(enhanceTables);tableObserver.observe(document.querySelector('#content'),{childList:true,subtree:true});
if(state.token)boot();
</script>
</body></html>
